Feature: Policy quote
  As a customer, I want to fill details
  And get quotes for policies
  

  Background: User navigates to home page
    Given I access URL "Application_URL"

  @test @tc1
  Scenario: Validate user is allowed to fill details fields
    When I select "Title" in "Home_DetailsPage_TitleOption"
    And I enter "First_Name" in "Home_DetailsPage_FirstNameField"
    And I enter "Last_Name" in "Home_DetailsPage_LastNameField"
    And I select "DOB_Day" in "Home_DetailsPage_DOB_DayOption"
    And I select "DOB_Month" in "Home_DetailsPage_DOB_MonthOption"
    And I select "DOB_Year" in "Home_DetailsPage_DOB_YearOption"
    And I select "Marital_Status" in "Home_DetailsPage_Marital_Status_Option"
    And I choose category as "Occupation" from "Home_DetailsPage_Occupation_Field"
    And I click on "Home_DetailsPage_Smoke_Option_No"
    And I enter "Mobile_Number" in "Home_DetailsPage_Mobile_Number_Field"
    And I enter "Email" in "Home_DetailsPage_Email_Field"
    And I click on "Home_DetailsPage_Statement_AboutYou_DoYouAgree_Iagree_Option"
    And I choose category as "Property_Address_Field" from "Home_DetailsPage_Property_Address_Field"
    And I click on "Home_DetailsPage_EnterAdrress_Button"
    And I enter "Property_AddressLine1_Field" in "Home_DetailsPage_EnterAdrress_AddressLineFirst_Field"
    And I enter "Property_AddressLine2_Field" in "Home_DetailsPage_EnterAdrress_AddressLineSecond_Field"
    And I enter "Property_AddressTown_Field" in "Home_DetailsPage_EnterAdrress_AddressTown_Field"
    And I enter "Property_AddressPostcode_Field" in "Home_DetailsPage_EnterAdrress_AddressPostCode_Field"
    And I click on "Home_DetailsPage_SaveAddress_Button"
    And I click on "Home_DetailsPage_Correspondence_Address_Option_Yes"
    And I select "Property_Type_Option" in "Home_DetailsPage_Property_Type_Option"
    And I select "Property_Type" in "Home_DetailsPage_Property_Type"
    And I enter "Area_Field" in "Home_DetailsPage_Area_Field"
    And I enter "Property_Year" in "Home_DetailsPage_PropertyYear_Field"
    And I select "Bedroom_Option" in "Home_DetailsPage_Bedroom_Option"
    And I select "Property_Ownership_Option" in "Home_DetailsPage_Property_Ownership_Option"
    And I select "Property_Occupied_BY_Option" in "Home_DetailsPage_Property_Occupied_BY_Option"
    And I select "Property_Occupied_Time_Option" in "Home_DetailsPage_Property_Occupied_Time_Option"
    And I click on "Home_DetailsPage_Tree_Height_Option_No"
    And I click on "Home_DetailsPage_Flat_Roof_Option_No"
    And I click on "Home_DetailsPage_Statement_AboutProperty_DoYouAgree_Iagree_Option"
    And I click on "Home_DetailsPage_Safety_And_Security_Key_Operated_Option_No"
    And I click on "Home_DetailsPage_Safety_And_Security_Front_Door_Lockable_Option_No"
    And I click on "Home_DetailsPage_Safety_And_Security_French_Patio_Door_Option_No"
    And I click on "Home_DetailsPage_Safety_And_Security_External_Door_Option_No"
    And I click on "Home_DetailsPage_Safety_And_Security_Burglar_Alarm_Option_No"
    And I click on "Home_DetailsPage_Joint_Policy_Option_No"
    And I select "Insurance_History_Years_Held_Option" in "Home_DetailsPage_Insurance_History_Years_Held_Option"
    And I click on "Home_DetailsPage_Insurance_History_Past_3_Years_Claim_Option_No"
    And I click on "Home_DetailsPage_About_Cover_Start_Field_Today"
    And I select "About_Cover_Insurance_Type" in "Home_DetailsPage_About_Cover_Insurance_Type"
    And I enter "Cost" in "Home_DetailsPage_About_Cover_CurrencyField"
    And I enter "Rebuild_Cost" in "Home_DetailsPage_About_Cover_RebuildCostField"
    And I click on "Home_DetailsPage_About_Cover_UpgradeField_Option_No"
    And I select "About_Cover_Standard_Access_Option" in "Home_DetailsPage_About_Cover_Standard_Access_Option"
    And I click on "Home_DetailsPage_GoToCompareQuotes_Button"
    Then I should see "Home_QuotePage_Quote_Message"